language: r
cache: packages

install:
  - Rscript -e "install.packages('')
  
script:
  - Rscript forecast.R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
